# Application configuration
quarkus.application.name=orders
quarkus.application.version=1.0.0
quarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21
# Database configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:orders}
# Health check configuration
quarkus.smallrye-health.root-path=/health
quarkus.health.livenessPath=/health/live
quarkus.health.readinessPath=/health/ready
# OpenAPI and Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/openapi
quarkus.smallrye-openapi.info-title=Orders API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API for orders microservice
# ports
quarkus.http.host=0.0.0.0
quarkus.http.port=${HTTP_PORT:8088}
#quarkus.http.ssl-port=${HTTP_SSL_PORT:8083}
# logging
quarkus.log.level=INFO
quarkus.log.handlers=INFO_FILE,ERR_FILE,EXCEPT_FILE
# logging console
quarkus.log.console.enable=true
quarkus.log.console.level=ALL
quarkus.log.console.format=[%-5p] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] [%C{1}] %s%e%n